### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by diegojgris** [oceam/EasyMPE#2]
Traceback (most recent call last):
  File "EasyMPE_main.py", line 447, in application
    self.field_image, aff, self.y_offset, self.x_offset)
  File "EasyMPE_plot_identification.py", line 121, in MPE
    col = True)
  File "EasyMPE_plot_identification.py", line 634, in draw_separation_lines
    width = (sum(end) - sum(start))/len(start) + margin
UnboundLocalError: local variable 'margin' referenced before assignment

**Comment by diegojgris** [comment]
I fixed in my pull request #3
